# KiyArch Midnight Forge
font_family Cascadia Code NF
font_size 11.0
background #0b0d0f
foreground #f1eee8
selection_background #2a3036
selection_foreground #f1eee8
cursor #e87832
cursor_text_color #0b0d0f
url_color #58a6a6
active_border_color #e87832
inactive_border_color #2a3036
bell_border_color #e0a84b
color0 #0b0d0f
color1 #d65d5d
color2 #58a66f
color3 #e0a84b
color4 #5f88b8
color5 #a97ab8
color6 #58a6a6
color7 #d8d5cf
color8 #555c62
color9 #ef7777
color10 #78bf8b
color11 #ffb15c
color12 #7fa9d8
color13 #c398d0
color14 #7bc4c4
color15 #f1eee8
window_padding_width 12
confirm_os_window_close 0
